version: "3.8"

services:
  # Production monitoring stack
  prometheus:
    image: prom/prometheus:latest
    container_name: qoder-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./load-testing/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./load-testing/monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./monitoring/prometheus/production-alert-rules.yml:/etc/prometheus/production-alert-rules.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: qoder-grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: qoder-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
    networks:
      - monitoring

  # Application metrics exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: qoder-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - monitoring

  # Redis metrics
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: qoder-redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - monitoring
      - qoder-network

  # PostgreSQL metrics
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: qoder-postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:your-password@postgres:5432/qoder_resume?sslmode=disable
    networks:
      - monitoring
      - qoder-network

  # Application uptime monitoring
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: qoder-uptime-kuma
    ports:
      - "3003:3001"
    volumes:
      - uptime_data:/app/data
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:
  uptime_data:

networks:
  monitoring:
    driver: bridge
  qoder-network:
    external: true
