config:
  target: 'http://localhost:3000'
  phases:
    # Smoke Test Phase
    - duration: 300
      arrivalRate: 1
      name: 'Smoke Test'
    # Warm-up Phase  
    - duration: 120
      arrivalRate: 10
      name: 'Warm-up'
    # Load Test Phase
    - duration: 600
      arrivalRate: 50
      name: 'Load Test'
    # Stress Test Phase
    - duration: 300
      arrivalRate: 100
      name: 'Stress Test'
    # Cool-down Phase
    - duration: 120
      arrivalRate: 10
      name: 'Cool-down'

  # HTTP settings
  http:
    timeout: 30000
    pool: 50

  # WebSocket settings  
  ws:
    maxMessages: 100

  # Payload settings
  payload:
    path: './test-data'
    fields:
      - 'user_id'
      - 'email' 
      - 'resume_content'

  # Reporting
  statsInterval: 10
  output: 
    - json
    - html

scenarios:
  # Authentication flow
  - name: 'User Authentication'
    weight: 20
    flow:
      - post:
          url: '/api/auth/login'
          json:
            email: '{{ email }}'
            password: 'testpass123'
      - think: 1

  # Resume operations  
  - name: 'Resume Management'
    weight: 30
    flow:
      - get:
          url: '/api/resumes'
          headers:
            Authorization: 'Bearer {{ token }}'
      - post:
          url: '/api/resumes/upload'
          formData:
            file: '@./test-data/sample-resume.pdf'
          headers:
            Authorization: 'Bearer {{ token }}'
      - think: 2

  # AI Analysis
  - name: 'AI Processing'
    weight: 25
    flow:
      - post:
          url: '/api/ai/analyze'
          json:
            resumeId: '{{ resumeId }}'
            options:
              includeATS: true
              includeKeywords: true
          headers:
            Authorization: 'Bearer {{ token }}'
      - think: 5

  # Admin Operations
  - name: 'Admin Dashboard'
    weight: 15
    flow:
      - get:
          url: '/api/admin/analytics/metrics'
          headers:
            Authorization: 'Bearer {{ adminToken }}'
      - get:
          url: '/api/admin/users'
          qs:
            page: 1
            limit: 20
          headers:
            Authorization: 'Bearer {{ adminToken }}'
      - think: 1

  # Job Applications
  - name: 'Job Tracking'  
    weight: 10
    flow:
      - get:
          url: '/api/job-applications'
          headers:
            Authorization: 'Bearer {{ token }}'
      - post:
          url: '/api/job-applications'
          json:
            companyName: 'Test Company'
            position: 'Software Engineer'
            status: 'applied'
          headers:
            Authorization: 'Bearer {{ token }}'

# Performance expectations
expect:
  - statusCode: 200
  - contentType: json
  - responseTime: 
      median: 500
      p95: 1000
      p99: 2000

# Monitoring and alerts
monitoring:
  - plugin: 'cloudwatch'
    region: 'us-east-1'
  - plugin: 'datadog'
    apiKey: '{{ DATADOG_API_KEY }}'