version: '3.8'

services:
  # Main Application (Monolith)
  qoder-resume:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - "3000:3000"  # Frontend
      - "3002:3002"  # Backend API
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    volumes:
      - upload_data:/app/uploads
    networks:
      - qoder-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: qoder_resume
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qoder-network

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - qoder-network
    command: redis-server --appendonly yes

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - qoder-resume
    networks:
      - qoder-network

volumes:
  postgres_data:
  redis_data:
  upload_data:

networks:
  qoder-network:
    driver: bridge