filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/qoder-resume/*.log
    fields:
      service: qoder-resume
      environment: ${ENVIRONMENT:development}
    fields_under_root: true
    multiline.pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}"
    multiline.negate: true
    multiline.match: after
    json.keys_under_root: true
    json.add_error_key: true

  - type: docker
    enabled: true
    containers.ids:
      - "*"
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
