server.name: "qoder-kibana"
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://elasticsearch:9200"]

# Security
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "qoder-resume-kibana-encryption-key-32-chars"

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true

# Dashboard settings
server.defaultRoute: "/app/dashboards"

# Logging
logging.appenders:
  file:
    type: file
    fileName: /var/log/kibana.log
    layout:
      type: json

logging.root:
  appenders:
    - default
    - file
  level: info
